---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crossplane
  namespace: argocd
  # finalizers:
  #   - resources-finalizer.argocd.argoproj.io
  annotations:
  #   argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/sync-wave: "-1"
    # argocd.argoproj.io/hook: PreSync
spec:
  project: default
  source:
    chart: crossplane
    repoURL: https://charts.crossplane.io/stable
    targetRevision: 1.12.2
    helm:
      releaseName: crossplane
  destination:
    server: https://kubernetes.default.svc
    namespace: crossplane-system
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - CreateNamespace=true
